#!/bin/bash
while true;
do 
    inotifywait -re modify --exclude '\.(sw*|pyc)' .
    clear
    TIME=`date`
    echo ===========================================
    echo $TIME
    time make clean test
    echo $TIME
    echo ===========================================
done
